evolution:
  is_shared_buffer: false
  population: 2
  softmax_temperature: 1.0
  use_default_configration: true
general:
  actor_gpu_usage: 0.1
  actor_processes: 6
  completion_reward: 195
  episodes_per_update: 16
  gpu_usage: 0.9
  gym_env: CartPole-v0
  max_path_slack: 1.5
  max_steps: 400
  model_updates_per_cycle: 40
  name: null
  random_seed: 123
  save_model_every_cycles: 100
  updates_cycle_count: 10000
  write_train_summaries: 1000
model:
  batch_size: 20
  buffer_size: 100000
  epsilon: 0.8
  epsilon_decay: 0.995
  epsilon_min: 0.01
  gamma: 0.9
test:
  number_of_episodes_per_actor: 50
  show_best: false
  test_every_cycles: 50
