

general:
  name:


  gym_env: 'CartPole-v0'
  completion_reward: 195

  #gym_env: 'Acrobot-v1'
  #completion_reward: -40

  #gym_env: 'MountainCar-v0'
  #completion_reward: 195

  #gym_env: 'LunarLander-v2'
  #completion_reward: 195


  random_seed: 123
  updates_cycle_count: 10000
  episodes_per_update: 16
  model_updates_per_cycle: 40
  #model_updates_per_cycle: 400
  #model_updates_per_cycle: 100
  max_path_slack: 1.5
  gpu_usage: 0.9
  actor_gpu_usage: 0.1
#  actor_processes: 2
  actor_processes: 6
  write_train_summaries: 1000
  save_model_every_cycles: 100
  #max_steps: 1000 #ll
  #max_steps: 400 #ab
  max_steps: 400 #cp

model:
  buffer_size: 10000
  #batch_size: 128
  #batch_size: 512 #ll
  batch_size: 64 #cp
  #gamma: 0.99  #ll
  gamma: 0.9 #cp

  epsilon: 0.9
  #epsilon_min: 0.25 #ll cp
  epsilon_min: 0.01 #ab
  #epsilon_decay: 0.9995
  epsilon_decay: 0.995 #ab


test:
  test_every_cycles: 50
  number_of_episodes_per_actor: 50
  show_best: True
  #show_best: False

evolution:
  population: 10
  softmax_temperature: 1.0
  #is_shared_buffer: False
  is_shared_buffer: True
  use_default_configration: True  # to benchmark vs regular agent
#  use_default_configration: False










